/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisup;

import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author andre
 */
public class CadastroFornecedorForm extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedorForm
     */
    public CadastroFornecedorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCodigo = new javax.swing.JLabel();
        EdtCodigo = new javax.swing.JTextField();
        LblRazao = new javax.swing.JLabel();
        EdtRazao = new javax.swing.JTextField();
        RdbPessoaJuridica = new javax.swing.JRadioButton();
        RdbPessoaFisica = new javax.swing.JRadioButton();
        LblFantasia = new javax.swing.JLabel();
        EdtFantasia = new javax.swing.JTextField();
        EdtCnpj = new javax.swing.JFormattedTextField();
        LblCnpj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblCodigo.setText("Código.:");

        LblRazao.setText("Razão Social.:");

        RdbPessoaJuridica.setText("Pessoa Jurídica");
        RdbPessoaJuridica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RdbPessoaJuridicaItemStateChanged(evt);
            }
        });

        RdbPessoaFisica.setText("Pessoa Física");
        RdbPessoaFisica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RdbPessoaFisicaItemStateChanged(evt);
            }
        });

        LblFantasia.setText("Nome Fantasia.:");

        try {
            EdtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LblCnpj.setText("Cnpj.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LblCodigo)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(LblRazao))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(EdtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(RdbPessoaJuridica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addComponent(RdbPessoaFisica))
                        .addComponent(EdtRazao)
                        .addComponent(LblFantasia)
                        .addComponent(EdtFantasia))
                    .addComponent(LblCnpj)
                    .addComponent(EdtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdbPessoaJuridica)
                    .addComponent(RdbPessoaFisica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblRazao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblFantasia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RdbPessoaJuridicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RdbPessoaJuridicaItemStateChanged
        if (RdbPessoaJuridica.isSelected()) {
            LblRazao.setText("Razão Social.:");
            RdbPessoaFisica.setSelected(false);
            LblFantasia.setText("Nome Fantasia.:");
            LblCnpj.setText("Cnpj.:");
            EdtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(Mascaras.cnpj()));
        }
        if(!RdbPessoaJuridica.isSelected()){
            if(!RdbPessoaFisica.isSelected()){
                RdbPessoaJuridica.setSelected(true);
            }
        }
    }//GEN-LAST:event_RdbPessoaJuridicaItemStateChanged

    private void RdbPessoaFisicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RdbPessoaFisicaItemStateChanged
        if (RdbPessoaFisica.isSelected()) {
            LblRazao.setText("Nome.:");
            RdbPessoaJuridica.setSelected(false);
            LblFantasia.setText("Apelido.:");
            LblCnpj.setText("Rg.:");
            EdtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(Mascaras.cpf()));
        }
        if(!RdbPessoaFisica.isSelected()){
            if(!RdbPessoaJuridica.isSelected()){
                RdbPessoaFisica.setSelected(true);
            }
        }
    }//GEN-LAST:event_RdbPessoaFisicaItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RdbPessoaJuridica.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedorForm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField EdtCnpj;
    private javax.swing.JTextField EdtCodigo;
    private javax.swing.JTextField EdtFantasia;
    private javax.swing.JTextField EdtRazao;
    private javax.swing.JLabel LblCnpj;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblFantasia;
    private javax.swing.JLabel LblRazao;
    private javax.swing.JRadioButton RdbPessoaFisica;
    private javax.swing.JRadioButton RdbPessoaJuridica;
    // End of variables declaration//GEN-END:variables

}
